a={}
name= input("enter your name :")
lang =input("enter your fav language :")
a.update({name : lang})
name= input("enter your name :")
lang =input("enter your fav language :")
a.update({name : lang})
name= input("enter your name :")
lang =input("enter your fav language :")
a.update({name : lang})
name= input("enter your name :")
lang =input("enter your fav language :")
a.update({name : lang})
name= input("enter your name :")
lang =input("enter your fav language :")
a.update({name : lang})
print(a)